// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoblrxdogaassdtifeiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYmxyeGRvZ2Fhc3NkdGlmZWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDk5NjUsImV4cCI6MjA2OTcyNTk2NX0.FR6FIG9va0Y-I4NayBmKg4ZxsQO16aFKbWYfm_thZA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});